apiVersion: v1
kind: Pod 
metadata:
  name: hostname-printer
spec:
  containers:
    - name: hostname-container
      image: arjundandagi/kobo:q1
      env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
  restartPolicy: Never
                 
